/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fxj_ffmpegdecoder01_NativePlayer */

#ifndef _Included_com_fxj_ffmpegdecoder01_NativePlayer
#define _Included_com_fxj_ffmpegdecoder01_NativePlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fxj_ffmpegdecoder01_NativePlayer
 * Method:    playVideo
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_fxj_ffmpegdecoder01_NativePlayer_playVideo
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_fxj_ffmpegdecoder01_NativePlayer
 * Method:    getStringMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fxj_ffmpegdecoder01_NativePlayer_getStringMsg
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
